from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import Any
from utils.price_comparator import search_all_stores, get_cheapest_product

app = FastAPI(title="AI Price Comparison API")

# Define request schemas
class SearchQuery(BaseModel):
    query: str

class ImageUploadData(BaseModel):
    image_url: str
    optional_description: str | None = None

@app.get("/")
def read_root():
    return {"message": "Welcome to the AI Price Comparison API Prototype"}

@app.post("/identify-product")
def identify_product(data: ImageUploadData):
    """
    DAY 1-6 PLACEHOLDER FOR DANIEL: 
    This endpoint will take the uploaded image, run the AI Vision model,
    and return the extracted keywords/query.
    """
    # TODO: Integrate image_recognition.py and query_builder.py here
    return {
        "status": "pending_ai_integration",
        "mock_generated_query": "black running shoe"
    }

@app.post("/compare")
def compare_prices(request: SearchQuery):
    """
    DAY 7 INTEGRATION: 
    Takes a search query (eventually generated by the AI model) 
    and returns the full price comparison across all stores.
    """
    if not request.query:
        raise HTTPException(status_code=400, detail="Query string is required")
    
    # 1. Fetch from all scrapers concurrently
    all_results = search_all_stores(request.query)
    
    # 2. Determine the best option
    cheapest_product = get_cheapest_product(all_results)
    
    return {
        "query": request.query,
        "total_results_found": len(all_results),
        "cheapest_option": cheapest_product,
        "all_results": all_results  # Already sorted from lowest to highest price
    }
